mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from oroll import views as oroll_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', login_required(oroll_views.IndexView.as_view()), name = 'root'),
    url(r'^oroll/', include('oroll.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/signup$', oroll_views.CreateUserView.as_view(), name = 'signup'),
    url(r'^accounts/signup/done$', oroll_views.RegisteredView.as_view(), name = 'create_user_done'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

oroll/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from . import views

app_name = 'oroll'

urlpatterns = [
        url(r'^$', login_required(views.IndexView.as_view()), name = 'index'),
        url(r'^upload$', views.upload, name = 'upload'),
        url(r'^profile/(?P<pk>[0-9]+)/$', login_required(views.ProfileView.as_view()), name='profile'),
]

oroll/models.py
from django.db import models
from django.conf import settings

# Create your models here.

def user_path(instance, filename):
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(10)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '%s/%s.%s' % (instance.owner.username, pid, extension)


class Photo(models.Model):
    title = models.CharField(max_length = 200, blank = False, default = '')
    image = models.ImageField(upload_to = user_path)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    thumbnail_image = models.ImageField(blank = True)
    url = models.URLField(blank = False, default = '')
    comment = models.CharField(max_length = 500)
    pub_date = models.DateTimeField(auto_now_add = True)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    nickname = models.CharField(max_length = 50)
    profile_photo = models.ImageField(blank = True)

oroll/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Photo

class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit = True):
        user = super(CreateUserForm, self).save(commit = False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class UploadForm(forms.ModelForm):
    comment = forms.CharField(max_length = 500)
    class Meta:
        model = Photo
        exclude = ('thumbnail_image', 'owner')

oroll/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
#from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import CreateUserForm, UploadForm
# Create your views here.

@login_required
def upload(request):
    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit = False)
            photo.owner = request.user
            form.save()
            return redirect('oroll:index')
    form = UploadForm()
    return render(request, 'oroll/upload.html', {'form':form})

class IndexView(ListView):
    # model = Photo
    context_object_name = 'user_photo_list'
    paginate_by = 10
    #template_name = 'oroll/index.html'

    def get_queryset(self):
        user = self.request.user
        return user.photo_set.all().order_by('-pub_date')

class CreateUserView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CreateUserForm
    #form_class = UserCreationForm
    success_url = reverse_lazy('create_user_done')

class RegisteredView(TemplateView):
    template_name = 'registration/signup_done.html'


class ProfileView(DetailView):
    context_object_name = 'profile_user'
    model = User
    template_name = 'oroll/profile.html'

oroll/templates/oroll/base.html
<!DOCTYPE html>
<html lang="ko">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<title>Oroll</title>
		
		<!-- Bootstrap -->
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'oroll/style.css' %}">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'oroll:index' %}"> <span class="glyphicon glyphicon-camera"> </span> Oroll </a>
				</div>
				
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_active %}
						<li><a href="{% url 'oroll:profile' user.pk %}"> <span class="glyphicon glyphicon-heart"></span> {{user.username}}</a></li>
						<li><a href="{% url 'logout' %}">Logout</a></li>
						{% else %}
						<li><a href="{% url 'login' %}"> <span class="glyphicon glyphicon-user"></span> Login</a></li>
						<li><a href="{% url 'admin:index' %}">Admin</a></li>
						{% endif %}
					</ul>
				</div> <!-- /.navbar-collapse -->
			</div> <!-- /.container-fluid -->
		</nav>
		<div class="container">
			<div>
				{% block content %}
				{% endblock %}
			</div>
		</div>
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</body>
</html>

oroll/templates/oroll/photo_list.html
{% extends 'oroll/base.html' %}
{% block content %}
<h1>오늘의 시나리오, Oroll</h1>
<p><a class="btn btn-primary" href="{% url 'oroll:upload' %}">업로드</a></p>

{% if user_photo_list %}
{% for photo in user_photo_list %}
<div class="panel panel-default" align="center">
	<div class="panel-heading"><h4>{{ photo.title }}</h4></div>
	<p>작성자 : {{ photo.owner.username }}</p>
	<div class="panel-body">
		{% if photo.image.width > 800 %}
		<p>
		<img src='{{ photo.image.url }}' width='600'>
		<br>
		{% else %}
		<p>
		<img src='{{ photo.image.url }}'><br>
		{% endif %}
		<a href="{{ photo.url }}">{{ photo.url }}</a>
		<br>
		{{ photo.comment }}
		</p>
	</div>
</div>
{% endfor %}
{% else %}
<h4>아직 등록된 시나리오가 없네요. 자신의 작품을 업로드해보세요!</h4>
{% endif %}

<!-- pagination nav -->
{% if is_paginated %}
<nav aria-label="...">
	<ul class=pager>
		{% if page_obj.has_previous %}
		<li><a href="{% url 'oroll:index' %}?page={{ page_obj.previous_page_number }}">이전</a></li>
		{% endif %}
		<li> <a href="#">페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} </a></li>
		{% if page_obj.has_next %}
		<li><a href="{% url 'oroll:index' %}?page={{ page_obj.next_page_number }}">다음</a></li>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock %}

oroll/templates/oroll/profile.html
{% extends 'oroll/base.html' %}
{% block content %}

{% load staticfiles %}

<div class="row">
	<div class="col-xs-6 col-md-3">
		{% if profile_user.profile.profile_photo %}
		<img class="round" src="{{profile_user.profile.profile_photo.url}}" width="200" height="200">
		{% else %}
		<img class="round" src="{% static 'oroll/images/아니.jpg' %}" width="200" height="200">
		{% endif %}
	</div>

	<div class="col-xs-6 col-md-3">
		{% if profile_user.profile.nickname %}
		<h2>{{ profile_user.profile.nickname }}</h2>
		{% endif %}
		{% if user == profile_user %}
		<a href="#">
			<button type="button" class="btn btn-default">프로필 편집</button></a></h2>
		{% endif %}
		<h3> username: {{ profile_user.username }}<br>
			{% if profile_user.first_name is not None %}
			name: {{ profile_user.first_name }} {{ profile_user.last_name }} <br>
			{% endif %}
		</h3>
	</div>
</div>

{% endblock %}

oroll/templates/oroll/upload.html
{% extends 'oroll/base.html' %}
{% block content %}
<h1>Oroll Post Upload</h1>

<form action = "{% url 'oroll:upload' %}" method = "POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Upload">
</form>

{% endblock %}